# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: activity_log.sql
import pydantic
from typing import Any, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


CREATE_ACTIVITY_LOG = """-- name: create_activity_log \\:one
INSERT INTO activity_log (user_id, action, details, ip_address)
VALUES (:p1, :p2, :p3, :p4)
RETURNING activity_id, user_id, action, details, ip_address, created_at
"""


class CreateActivityLogParams(pydantic.BaseModel):
    user_id: Optional[int]
    action: str
    details: Optional[Any]
    ip_address: str


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_activity_log(self, arg: CreateActivityLogParams) -> Optional[models.ActivityLog]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_ACTIVITY_LOG), {
            "p1": arg.user_id,
            "p2": arg.action,
            "p3": arg.details,
            "p4": arg.ip_address,
        })).first()
        if row is None:
            return None
        return models.ActivityLog(
            activity_id=row[0],
            user_id=row[1],
            action=row[2],
            details=row[3],
            ip_address=row[4],
            created_at=row[5],
        )
