# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: admin.sql
import datetime
import pydantic
from typing import AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


CREATE_ADMIN = """-- name: create_admin \\:one
INSERT INTO admins (user_id, fName, lName)
VALUES (:p1,:p2,:p3)
RETURNING user_id, fname, lname, active
"""


class CreateAdminParams(pydantic.BaseModel):
    user_id: int
    fname: str
    lname: str


GET_ADMIN = """-- name: get_admin \\:one
SELECT u.user_id, u.username, u.email, a.fName, a.lName, a.active, u.last_login, u.created_at
FROM admins a
INNER JOIN users u ON a.user_id = u.user_id
WHERE u.user_id = :p1
LIMIT 1
"""


class GetAdminRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    fname: str
    lname: str
    active: Optional[bool]
    last_login: datetime.datetime
    created_at: datetime.datetime


GET_ADMINS = """-- name: get_admins \\:many
SELECT u.user_id, u.username, u.email, a.fName, a.lName, a.active, u.last_login, u.created_at
FROM admins a
INNER JOIN users u ON a.user_id = u.user_id
"""


class GetAdminsRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    fname: str
    lname: str
    active: Optional[bool]
    last_login: datetime.datetime
    created_at: datetime.datetime


SET_IS_ADMIN_ACTIVE = """-- name: set_is_admin_active \\:one
UPDATE admins
SET active=:p2
WHERE user_id=:p1
RETURNING user_id, fname, lname, active
"""


class SetIsAdminActiveParams(pydantic.BaseModel):
    user_id: int
    active: Optional[bool]


UPDATE_ADMIN = """-- name: update_admin \\:one
UPDATE admins
SET fName = :p2, lName = :p3
WHERE user_id = :p1
RETURNING user_id, fname, lname, active
"""


class UpdateAdminParams(pydantic.BaseModel):
    user_id: int
    fname: str
    lname: str


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_admin(self, arg: CreateAdminParams) -> Optional[models.Admin]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_ADMIN), {"p1": arg.user_id, "p2": arg.fname, "p3": arg.lname})).first()
        if row is None:
            return None
        return models.Admin(
            user_id=row[0],
            fname=row[1],
            lname=row[2],
            active=row[3],
        )

    async def get_admin(self, *, user_id: int) -> Optional[GetAdminRow]:
        row = (await self._conn.execute(sqlalchemy.text(GET_ADMIN), {"p1": user_id})).first()
        if row is None:
            return None
        return GetAdminRow(
            user_id=row[0],
            username=row[1],
            email=row[2],
            fname=row[3],
            lname=row[4],
            active=row[5],
            last_login=row[6],
            created_at=row[7],
        )

    async def get_admins(self) -> AsyncIterator[GetAdminsRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_ADMINS))
        async for row in result:
            yield GetAdminsRow(
                user_id=row[0],
                username=row[1],
                email=row[2],
                fname=row[3],
                lname=row[4],
                active=row[5],
                last_login=row[6],
                created_at=row[7],
            )

    async def set_is_admin_active(self, arg: SetIsAdminActiveParams) -> Optional[models.Admin]:
        row = (await self._conn.execute(sqlalchemy.text(SET_IS_ADMIN_ACTIVE), {"p1": arg.user_id, "p2": arg.active})).first()
        if row is None:
            return None
        return models.Admin(
            user_id=row[0],
            fname=row[1],
            lname=row[2],
            active=row[3],
        )

    async def update_admin(self, arg: UpdateAdminParams) -> Optional[models.Admin]:
        row = (await self._conn.execute(sqlalchemy.text(UPDATE_ADMIN), {"p1": arg.user_id, "p2": arg.fname, "p3": arg.lname})).first()
        if row is None:
            return None
        return models.Admin(
            user_id=row[0],
            fname=row[1],
            lname=row[2],
            active=row[3],
        )
