# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: admin_issue_reports.sql
import pydantic
from typing import AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


CREATE_ADMIN_ISSUE_REPORT = """-- name: create_admin_issue_report \\:one
INSERT INTO admin_issue_reports (user_id, issue_type, description)
VALUES (:p1, :p2, :p3)
RETURNING report_id, user_id, issue_type, description, created_at, status
"""


class CreateAdminIssueReportParams(pydantic.BaseModel):
    user_id: int
    issue_type: models.AdminIssueType
    description: str


DELETE_ADMIN_ISSUE_REPORT = """-- name: delete_admin_issue_report \\:one
DELETE FROM admin_issue_reports
WHERE report_id = :p1
RETURNING report_id, user_id, issue_type, description, created_at, status
"""


GET_ADMIN_ISSUE_REPORTS = """-- name: get_admin_issue_reports \\:many
SELECT report_id, user_id, issue_type, description, created_at, status FROM admin_issue_reports
"""


GET_ADMIN_ISSUE_REPORTS_BY_USER = """-- name: get_admin_issue_reports_by_user \\:many
SELECT report_id, user_id, issue_type, description, created_at, status FROM admin_issue_reports
WHERE user_id = :p1
"""


UPDATE_ADMIN_ISSUE_REPORT_STATUS = """-- name: update_admin_issue_report_status \\:one
UPDATE admin_issue_reports
SET status = :p2
WHERE report_id = :p1
RETURNING report_id, user_id, issue_type, description, created_at, status
"""


class UpdateAdminIssueReportStatusParams(pydantic.BaseModel):
    report_id: int
    status: models.IssueStatus


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_admin_issue_report(self, arg: CreateAdminIssueReportParams) -> Optional[models.AdminIssueReport]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_ADMIN_ISSUE_REPORT), {"p1": arg.user_id, "p2": arg.issue_type, "p3": arg.description})).first()
        if row is None:
            return None
        return models.AdminIssueReport(
            report_id=row[0],
            user_id=row[1],
            issue_type=row[2],
            description=row[3],
            created_at=row[4],
            status=row[5],
        )

    async def delete_admin_issue_report(self, *, report_id: int) -> Optional[models.AdminIssueReport]:
        row = (await self._conn.execute(sqlalchemy.text(DELETE_ADMIN_ISSUE_REPORT), {"p1": report_id})).first()
        if row is None:
            return None
        return models.AdminIssueReport(
            report_id=row[0],
            user_id=row[1],
            issue_type=row[2],
            description=row[3],
            created_at=row[4],
            status=row[5],
        )

    async def get_admin_issue_reports(self) -> AsyncIterator[models.AdminIssueReport]:
        result = await self._conn.stream(sqlalchemy.text(GET_ADMIN_ISSUE_REPORTS))
        async for row in result:
            yield models.AdminIssueReport(
                report_id=row[0],
                user_id=row[1],
                issue_type=row[2],
                description=row[3],
                created_at=row[4],
                status=row[5],
            )

    async def get_admin_issue_reports_by_user(self, *, user_id: int) -> AsyncIterator[models.AdminIssueReport]:
        result = await self._conn.stream(sqlalchemy.text(GET_ADMIN_ISSUE_REPORTS_BY_USER), {"p1": user_id})
        async for row in result:
            yield models.AdminIssueReport(
                report_id=row[0],
                user_id=row[1],
                issue_type=row[2],
                description=row[3],
                created_at=row[4],
                status=row[5],
            )

    async def update_admin_issue_report_status(self, arg: UpdateAdminIssueReportStatusParams) -> Optional[models.AdminIssueReport]:
        row = (await self._conn.execute(sqlalchemy.text(UPDATE_ADMIN_ISSUE_REPORT_STATUS), {"p1": arg.report_id, "p2": arg.status})).first()
        if row is None:
            return None
        return models.AdminIssueReport(
            report_id=row[0],
            user_id=row[1],
            issue_type=row[2],
            description=row[3],
            created_at=row[4],
            status=row[5],
        )
