# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: admin.sql
import pydantic
from typing import Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


CREATE_ADMIN = """-- name: create_admin \\:one
INSERT INTO admins (user_id, fName, lName)
VALUES (:p1,:p2,:p3)
RETURNING user_id, fname, lname, active
"""


class CreateAdminParams(pydantic.BaseModel):
    user_id: int
    fname: str
    lname: str


SET_IS_ADMIN_ACTIVE = """-- name: set_is_admin_active \\:one
UPDATE admins
SET active=:p2
WHERE user_id=:p1
RETURNING user_id, fname, lname, active
"""


class SetIsAdminActiveParams(pydantic.BaseModel):
    user_id: int
    active: Optional[bool]


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_admin(self, arg: CreateAdminParams) -> Optional[models.Admin]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_ADMIN), {"p1": arg.user_id, "p2": arg.fname, "p3": arg.lname})).first()
        if row is None:
            return None
        return models.Admin(
            user_id=row[0],
            fname=row[1],
            lname=row[2],
            active=row[3],
        )

    async def set_is_admin_active(self, arg: SetIsAdminActiveParams) -> Optional[models.Admin]:
        row = (await self._conn.execute(sqlalchemy.text(SET_IS_ADMIN_ACTIVE), {"p1": arg.user_id, "p2": arg.active})).first()
        if row is None:
            return None
        return models.Admin(
            user_id=row[0],
            fname=row[1],
            lname=row[2],
            active=row[3],
        )
