# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: allergens.sql
from typing import AsyncIterator

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


GET_ALLERGENS = """-- name: get_allergens \\:many
SELECT allergen_id, allergen_name
FROM allergens
"""


GET_BUNDLE_ALLERGENS = """-- name: get_bundle_allergens \\:many
SELECT a.allergen_id
FROM allergens a
JOIN bundle_allergens ba ON ba.allergen_id = a.allergen_id
JOIN bundles b ON b.bundle_id = ba.bundle_id
WHERE b.bundle_id=:p1
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def get_allergens(self) -> AsyncIterator[models.Allergen]:
        result = await self._conn.stream(sqlalchemy.text(GET_ALLERGENS))
        async for row in result:
            yield models.Allergen(
                allergen_id=row[0],
                allergen_name=row[1],
            )

    async def get_bundle_allergens(self, *, bundle_id: int) -> AsyncIterator[int]:
        result = await self._conn.stream(sqlalchemy.text(GET_BUNDLE_ALLERGENS), {"p1": bundle_id})
        async for row in result:
            yield row[0]
