# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: allergens.sql
from typing import Iterator

import sqlalchemy

from internal.queries import models


GET_BUNDLE_ALLERGENS = """-- name: get_bundle_allergens \\:many
SELECT a.allergen_id
FROM allergens a
JOIN bundle_allergens ba ON ba.allergen_id = a.allergen_id
JOIN bundles b ON b.bundle_id = ba.bundle_id
WHERE b.bundle_id=:p1
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def get_bundle_allergens(self, *, bundle_id: int) -> Iterator[int]:
        result = self._conn.execute(sqlalchemy.text(GET_BUNDLE_ALLERGENS), {"p1": bundle_id})
        for row in result:
            yield row[0]
