# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: analytics.sql
import pydantic
from typing import AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


CREATE_GRAPH = """-- name: create_graph \\:one
INSERT INTO analytics_graphs (seller_id, graph_type)
VALUES (:p1, :p2)
RETURNING graph_id, seller_id, graph_type, created_at
"""


class CreateGraphParams(pydantic.BaseModel):
    seller_id: int
    graph_type: int


CREATE_GRAPH_SERIES = """-- name: create_graph_series \\:one
INSERT INTO analytics_series (graph_id, series_name, sort_index)
VALUES (:p1, :p2, :p3)
RETURNING series_id, graph_id, series_name, sort_index
"""


class CreateGraphSeriesParams(pydantic.BaseModel):
    graph_id: int
    series_name: str
    sort_index: int


DELETE_GRAPH_SERIES = """-- name: delete_graph_series \\:many
DELETE FROM analytics_series
WHERE graph_id=:p1
RETURNING series_id, graph_id, series_name, sort_index
"""


GET_GRAPH = """-- name: get_graph \\:one
SELECT graph_id, seller_id, graph_type, created_at
FROM analytics_graphs
WHERE seller_id=:p1 AND graph_type=:p2
LIMIT 1
"""


class GetGraphParams(pydantic.BaseModel):
    seller_id: int
    graph_type: int


GET_GRAPH_SERIES = """-- name: get_graph_series \\:many
SELECT series_id, graph_id, series_name, sort_index
FROM analytics_series
WHERE graph_id=:p1
ORDER BY sort_index
"""


GET_GRAPHS = """-- name: get_graphs \\:many
SELECT graph_id, seller_id, graph_type, created_at
FROM analytics_graphs
WHERE seller_id=:p1
"""


GET_GRAPHS_TYPES = """-- name: get_graphs_types \\:many
SELECT graph_type_id, chart_type, graph_summary, x_axis_label, y_axis_label
FROM analytics_graphs_types
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_graph(self, arg: CreateGraphParams) -> Optional[models.AnalyticsGraph]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_GRAPH), {"p1": arg.seller_id, "p2": arg.graph_type})).first()
        if row is None:
            return None
        return models.AnalyticsGraph(
            graph_id=row[0],
            seller_id=row[1],
            graph_type=row[2],
            created_at=row[3],
        )

    async def create_graph_series(self, arg: CreateGraphSeriesParams) -> Optional[models.AnalyticsSeries]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_GRAPH_SERIES), {"p1": arg.graph_id, "p2": arg.series_name, "p3": arg.sort_index})).first()
        if row is None:
            return None
        return models.AnalyticsSeries(
            series_id=row[0],
            graph_id=row[1],
            series_name=row[2],
            sort_index=row[3],
        )

    async def delete_graph_series(self, *, graph_id: int) -> AsyncIterator[models.AnalyticsSeries]:
        result = await self._conn.stream(sqlalchemy.text(DELETE_GRAPH_SERIES), {"p1": graph_id})
        async for row in result:
            yield models.AnalyticsSeries(
                series_id=row[0],
                graph_id=row[1],
                series_name=row[2],
                sort_index=row[3],
            )

    async def get_graph(self, arg: GetGraphParams) -> Optional[models.AnalyticsGraph]:
        row = (await self._conn.execute(sqlalchemy.text(GET_GRAPH), {"p1": arg.seller_id, "p2": arg.graph_type})).first()
        if row is None:
            return None
        return models.AnalyticsGraph(
            graph_id=row[0],
            seller_id=row[1],
            graph_type=row[2],
            created_at=row[3],
        )

    async def get_graph_series(self, *, graph_id: int) -> AsyncIterator[models.AnalyticsSeries]:
        result = await self._conn.stream(sqlalchemy.text(GET_GRAPH_SERIES), {"p1": graph_id})
        async for row in result:
            yield models.AnalyticsSeries(
                series_id=row[0],
                graph_id=row[1],
                series_name=row[2],
                sort_index=row[3],
            )

    async def get_graphs(self, *, seller_id: int) -> AsyncIterator[models.AnalyticsGraph]:
        result = await self._conn.stream(sqlalchemy.text(GET_GRAPHS), {"p1": seller_id})
        async for row in result:
            yield models.AnalyticsGraph(
                graph_id=row[0],
                seller_id=row[1],
                graph_type=row[2],
                created_at=row[3],
            )

    async def get_graphs_types(self) -> AsyncIterator[models.AnalyticsGraphsType]:
        result = await self._conn.stream(sqlalchemy.text(GET_GRAPHS_TYPES))
        async for row in result:
            yield models.AnalyticsGraphsType(
                graph_type_id=row[0],
                chart_type=row[1],
                graph_summary=row[2],
                x_axis_label=row[3],
                y_axis_label=row[4],
            )
