# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: bundle.sql
import datetime
import decimal
import pydantic
from typing import Iterator, Optional

import sqlalchemy

from internal.queries import models


CREATE_BUNDLE = """-- name: create_bundle \\:one
INSERT INTO bundles (seller_id, bundle_name, description, total_qty, price, discount_percentage, window_start, window_end)
VALUES (:p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8)
RETURNING bundle_id, seller_id, bundle_name, description, total_qty, price, discount_percentage, window_start, window_end, created_at
"""


class CreateBundleParams(pydantic.BaseModel):
    seller_id: int
    bundle_name: str
    description: str
    total_qty: int
    price: decimal.Decimal
    discount_percentage: int
    window_start: datetime.datetime
    window_end: datetime.datetime


GET_BUNDLE = """-- name: get_bundle \\:one
SELECT bundle_id, seller_id, bundle_name, description, total_qty, price, discount_percentage, window_start, window_end, created_at
FROM bundles
WHERE bundle_id=:p1
LIMIT 1
"""


GET_BUNDLE_LOCK = """-- name: get_bundle_lock \\:one
SELECT bundle_id, seller_id, bundle_name, description, total_qty, price, discount_percentage, window_start, window_end, created_at
FROM bundles
WHERE bundle_id=:p1
FOR UPDATE
LIMIT 1
"""


GET_BUNDLES = """-- name: get_bundles \\:many
SELECT bundle_id, seller_id, bundle_name, description, total_qty, price, discount_percentage, window_start, window_end, created_at
FROM bundles
"""


GET_SELLERS_ACTIVE_BUNDLES = """-- name: get_sellers_active_bundles \\:many
SELECT bundle_id, seller_id, bundle_name, description, total_qty, price, discount_percentage, window_start, window_end, created_at
FROM bundles
WHERE seller_id=:p1 AND window_end >= NOW()
"""


GET_SELLERS_BUNDLE = """-- name: get_sellers_bundle \\:one
SELECT bundle_id, seller_id, bundle_name, description, total_qty, price, discount_percentage, window_start, window_end, created_at
FROM bundles
WHERE seller_id=:p1 AND bundle_id=:p2
LIMIT 1
"""


class GetSellersBundleParams(pydantic.BaseModel):
    seller_id: int
    bundle_id: int


GET_SELLERS_BUNDLES = """-- name: get_sellers_bundles \\:many
SELECT bundle_id, seller_id, bundle_name, description, total_qty, price, discount_percentage, window_start, window_end, created_at
FROM bundles
WHERE seller_id=:p1
"""


UPDATE_BUNDLE = """-- name: update_bundle \\:one
UPDATE bundles
SET bundle_name=:p3, description=:p4, total_qty=:p5, price=:p6, discount_percentage=:p7, window_start=:p8, window_end=:p9
WHERE bundle_id=:p1 AND seller_id=:p2
RETURNING bundle_id, seller_id, bundle_name, description, total_qty, price, discount_percentage, window_start, window_end, created_at
"""


class UpdateBundleParams(pydantic.BaseModel):
    bundle_id: int
    seller_id: int
    bundle_name: str
    description: str
    total_qty: int
    price: decimal.Decimal
    discount_percentage: int
    window_start: datetime.datetime
    window_end: datetime.datetime


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_bundle(self, arg: CreateBundleParams) -> Optional[models.Bundle]:
        row = self._conn.execute(sqlalchemy.text(CREATE_BUNDLE), {
            "p1": arg.seller_id,
            "p2": arg.bundle_name,
            "p3": arg.description,
            "p4": arg.total_qty,
            "p5": arg.price,
            "p6": arg.discount_percentage,
            "p7": arg.window_start,
            "p8": arg.window_end,
        }).first()
        if row is None:
            return None
        return models.Bundle(
            bundle_id=row[0],
            seller_id=row[1],
            bundle_name=row[2],
            description=row[3],
            total_qty=row[4],
            price=row[5],
            discount_percentage=row[6],
            window_start=row[7],
            window_end=row[8],
            created_at=row[9],
        )

    def get_bundle(self, *, bundle_id: int) -> Optional[models.Bundle]:
        row = self._conn.execute(sqlalchemy.text(GET_BUNDLE), {"p1": bundle_id}).first()
        if row is None:
            return None
        return models.Bundle(
            bundle_id=row[0],
            seller_id=row[1],
            bundle_name=row[2],
            description=row[3],
            total_qty=row[4],
            price=row[5],
            discount_percentage=row[6],
            window_start=row[7],
            window_end=row[8],
            created_at=row[9],
        )

    def get_bundle_lock(self, *, bundle_id: int) -> Optional[models.Bundle]:
        row = self._conn.execute(sqlalchemy.text(GET_BUNDLE_LOCK), {"p1": bundle_id}).first()
        if row is None:
            return None
        return models.Bundle(
            bundle_id=row[0],
            seller_id=row[1],
            bundle_name=row[2],
            description=row[3],
            total_qty=row[4],
            price=row[5],
            discount_percentage=row[6],
            window_start=row[7],
            window_end=row[8],
            created_at=row[9],
        )

    def get_bundles(self) -> Iterator[models.Bundle]:
        result = self._conn.execute(sqlalchemy.text(GET_BUNDLES))
        for row in result:
            yield models.Bundle(
                bundle_id=row[0],
                seller_id=row[1],
                bundle_name=row[2],
                description=row[3],
                total_qty=row[4],
                price=row[5],
                discount_percentage=row[6],
                window_start=row[7],
                window_end=row[8],
                created_at=row[9],
            )

    def get_sellers_active_bundles(self, *, seller_id: int) -> Iterator[models.Bundle]:
        result = self._conn.execute(sqlalchemy.text(GET_SELLERS_ACTIVE_BUNDLES), {"p1": seller_id})
        for row in result:
            yield models.Bundle(
                bundle_id=row[0],
                seller_id=row[1],
                bundle_name=row[2],
                description=row[3],
                total_qty=row[4],
                price=row[5],
                discount_percentage=row[6],
                window_start=row[7],
                window_end=row[8],
                created_at=row[9],
            )

    def get_sellers_bundle(self, arg: GetSellersBundleParams) -> Optional[models.Bundle]:
        row = self._conn.execute(sqlalchemy.text(GET_SELLERS_BUNDLE), {"p1": arg.seller_id, "p2": arg.bundle_id}).first()
        if row is None:
            return None
        return models.Bundle(
            bundle_id=row[0],
            seller_id=row[1],
            bundle_name=row[2],
            description=row[3],
            total_qty=row[4],
            price=row[5],
            discount_percentage=row[6],
            window_start=row[7],
            window_end=row[8],
            created_at=row[9],
        )

    def get_sellers_bundles(self, *, seller_id: int) -> Iterator[models.Bundle]:
        result = self._conn.execute(sqlalchemy.text(GET_SELLERS_BUNDLES), {"p1": seller_id})
        for row in result:
            yield models.Bundle(
                bundle_id=row[0],
                seller_id=row[1],
                bundle_name=row[2],
                description=row[3],
                total_qty=row[4],
                price=row[5],
                discount_percentage=row[6],
                window_start=row[7],
                window_end=row[8],
                created_at=row[9],
            )

    def update_bundle(self, arg: UpdateBundleParams) -> Optional[models.Bundle]:
        row = self._conn.execute(sqlalchemy.text(UPDATE_BUNDLE), {
            "p1": arg.bundle_id,
            "p2": arg.seller_id,
            "p3": arg.bundle_name,
            "p4": arg.description,
            "p5": arg.total_qty,
            "p6": arg.price,
            "p7": arg.discount_percentage,
            "p8": arg.window_start,
            "p9": arg.window_end,
        }).first()
        if row is None:
            return None
        return models.Bundle(
            bundle_id=row[0],
            seller_id=row[1],
            bundle_name=row[2],
            description=row[3],
            total_qty=row[4],
            price=row[5],
            discount_percentage=row[6],
            window_start=row[7],
            window_end=row[8],
            created_at=row[9],
        )
