# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: category.sql
from typing import Iterator

import sqlalchemy

from internal.queries import models


GET_BUNDLE_CATEGORIES = """-- name: get_bundle_categories \\:many
SELECT c.category_id
FROM category c
JOIN bundle_category bc ON bc.category_id = c.category_id
JOIN bundles b ON b.bundle_id = bc.bundle_id
WHERE b.bundle_id=:p1
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def get_bundle_categories(self, *, bundle_id: int) -> Iterator[int]:
        result = self._conn.execute(sqlalchemy.text(GET_BUNDLE_CATEGORIES), {"p1": bundle_id})
        for row in result:
            yield row[0]
