# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: category.sql
from typing import AsyncIterator

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


GET_BUNDLE_CATEGORIES = """-- name: get_bundle_categories \\:many
SELECT c.category_id
FROM category c
JOIN bundle_category bc ON bc.category_id = c.category_id
JOIN bundles b ON b.bundle_id = bc.bundle_id
WHERE b.bundle_id=:p1
"""


GET_CATEGORIES = """-- name: get_categories \\:many
SELECT category_id, category_name
FROM category
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def get_bundle_categories(self, *, bundle_id: int) -> AsyncIterator[int]:
        result = await self._conn.stream(sqlalchemy.text(GET_BUNDLE_CATEGORIES), {"p1": bundle_id})
        async for row in result:
            yield row[0]

    async def get_categories(self) -> AsyncIterator[models.Category]:
        result = await self._conn.stream(sqlalchemy.text(GET_CATEGORIES))
        async for row in result:
            yield models.Category(
                category_id=row[0],
                category_name=row[1],
            )
