# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: consumer.sql
import dataclasses
from typing import Any, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from queries import models


CREATE_CONSUMER = """-- name: create_consumer \\:exec
INSERT INTO consumers (user_id, fName, lName)
VALUES (?, ?, ?)
"""


GET_CONSUMER = """-- name: get_consumer \\:one
SELECT users.user_id, email, fName, lName
FROM consumers
INNER JOIN users ON consumers.user_id=users.user_od
WHERE users.user_id=?
LIMIT 1
"""


@dataclasses.dataclass()
class GetConsumerRow:
    user_id: Any
    email: Any
    fname: Any
    lname: Any


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_consumer(self, *, user_id: Any, fname: Any, lname: Any) -> None:
        self._conn.execute(sqlalchemy.text(CREATE_CONSUMER), {"p1": user_id, "p2": fname, "p3": lname})

    def get_consumer(self, *, user_id: Any) -> Optional[GetConsumerRow]:
        row = self._conn.execute(sqlalchemy.text(GET_CONSUMER), {"p1": user_id}).first()
        if row is None:
            return None
        return GetConsumerRow(
            user_id=row[0],
            email=row[1],
            fname=row[2],
            lname=row[3],
        )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_consumer(self, *, user_id: Any, fname: Any, lname: Any) -> None:
        await self._conn.execute(sqlalchemy.text(CREATE_CONSUMER), {"p1": user_id, "p2": fname, "p3": lname})

    async def get_consumer(self, *, user_id: Any) -> Optional[GetConsumerRow]:
        row = (await self._conn.execute(sqlalchemy.text(GET_CONSUMER), {"p1": user_id})).first()
        if row is None:
            return None
        return GetConsumerRow(
            user_id=row[0],
            email=row[1],
            fname=row[2],
            lname=row[3],
        )
