# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: consumer.sql
import datetime
import pydantic
from typing import Optional

import sqlalchemy

from internal.queries import models


CREATE_CONSUMER = """-- name: create_consumer \\:one
INSERT INTO consumers (user_id, fName, lName)
VALUES (:p1, :p2, :p3)
RETURNING user_id, fname, lname
"""


class CreateConsumerParams(pydantic.BaseModel):
    user_id: int
    fname: str
    lname: str


GET_CONSUMER = """-- name: get_consumer \\:one
SELECT u.user_id, u.email, c.fName, c.lName, u.last_login, u.created_at
FROM consumers  c
INNER JOIN users u ON c.user_id = u.user_id
WHERE u.user_id=:p1
LIMIT 1
"""


class GetConsumerRow(pydantic.BaseModel):
    user_id: int
    email: str
    fname: str
    lname: str
    last_login: datetime.datetime
    created_at: datetime.datetime


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_consumer(self, arg: CreateConsumerParams) -> Optional[models.Consumer]:
        row = self._conn.execute(sqlalchemy.text(CREATE_CONSUMER), {"p1": arg.user_id, "p2": arg.fname, "p3": arg.lname}).first()
        if row is None:
            return None
        return models.Consumer(
            user_id=row[0],
            fname=row[1],
            lname=row[2],
        )

    def get_consumer(self, *, user_id: int) -> Optional[GetConsumerRow]:
        row = self._conn.execute(sqlalchemy.text(GET_CONSUMER), {"p1": user_id}).first()
        if row is None:
            return None
        return GetConsumerRow(
            user_id=row[0],
            email=row[1],
            fname=row[2],
            lname=row[3],
            last_login=row[4],
            created_at=row[5],
        )
