# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: consumer.sql
import datetime
import pydantic
from typing import Iterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


CREATE_CONSUMER = """-- name: create_consumer \\:one
INSERT INTO consumers (user_id, fName, lName)
VALUES (:p1, :p2, :p3)
RETURNING user_id, fname, lname
"""


class CreateConsumerParams(pydantic.BaseModel):
    user_id: int
    fname: str
    lname: str


GET_CONSUMER = """-- name: get_consumer \\:one
SELECT u.user_id, u.username, u.email, c.fName, c.lName, u.last_login, u.created_at
FROM consumers  c
INNER JOIN users u ON c.user_id = u.user_id
WHERE u.user_id=:p1
LIMIT 1
"""


class GetConsumerRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    fname: str
    lname: str
    last_login: datetime.datetime
    created_at: datetime.datetime


GET_CONSUMERS = """-- name: get_consumers \\:many
SELECT u.user_id, u.username, u.email, c.fName, c.lName, u.last_login, u.created_at
FROM consumers c
INNER JOIN users u ON c.user_id = u.user_id
"""


class GetConsumersRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    fname: str
    lname: str
    last_login: datetime.datetime
    created_at: datetime.datetime


UPDATE_CONSUMER = """-- name: update_consumer \\:one
UPDATE consumers
SET fName=:p2, lName=:p3
WHERE user_id=:p1
RETURNING user_id, fname, lname
"""


class UpdateConsumerParams(pydantic.BaseModel):
    user_id: int
    fname: str
    lname: str


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_consumer(self, arg: CreateConsumerParams) -> Optional[models.Consumer]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_CONSUMER), {"p1": arg.user_id, "p2": arg.fname, "p3": arg.lname})).first()
        if row is None:
            return None
        return models.Consumer(
            user_id=row[0],
            fname=row[1],
            lname=row[2],
        )

    async def get_consumer(self, *, user_id: int) -> Optional[GetConsumerRow]:
        row = (await self._conn.execute(sqlalchemy.text(GET_CONSUMER), {"p1": user_id})).first()
        if row is None:
            return None
        return GetConsumerRow(
            user_id=row[0],
            username=row[1],
            email=row[2],
            fname=row[3],
            lname=row[4],
            last_login=row[5],
            created_at=row[6],
        )

    def get_consumers(self) -> Iterator[GetConsumersRow]:
        result = self._conn.execute(sqlalchemy.text(GET_CONSUMERS))
        for row in result:
            yield GetConsumersRow(
                user_id=row[0],
                username=row[1],
                email=row[2],
                fname=row[3],
                lname=row[4],
                last_login=row[5],
                created_at=row[6],
            )

    def update_consumer(self, arg: UpdateConsumerParams) -> Optional[models.Consumer]:
        row = self._conn.execute(sqlalchemy.text(UPDATE_CONSUMER), {"p1": arg.user_id, "p2": arg.fname, "p3": arg.lname}).first()
        if row is None:
            return None
        return models.Consumer(
            user_id=row[0],
            fname=row[1],
            lname=row[2],
        )
