# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: forecast.sql
import datetime
import decimal
import pydantic
from typing import AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


CREATE_FORECAST_INPUT = """-- name: create_forecast_input \\:one
INSERT INTO forecast_input (bundle_id, seller_id, category_id, day_of_week, window_start, window_end, is_holiday, temperature, weather_flag, observed_reservations, observed_no_shows)
VALUES (:p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10, :p11)
RETURNING input_id, bundle_id, seller_id, category_id, day_of_week, window_start, window_end, is_holiday, temperature, weather_flag, observed_reservations, observed_no_shows
"""


class CreateForecastInputParams(pydantic.BaseModel):
    bundle_id: int
    seller_id: int
    category_id: int
    day_of_week: models.DayOfWeek
    window_start: datetime.datetime
    window_end: datetime.datetime
    is_holiday: bool
    temperature: decimal.Decimal
    weather_flag: models.WeatherFlag
    observed_reservations: int
    observed_no_shows: int


GET_FORECAST_INPUTS_BY_SELLER = """-- name: get_forecast_inputs_by_seller \\:many
SELECT input_id, bundle_id, seller_id, category_id, day_of_week, window_start, window_end, is_holiday, temperature, weather_flag, observed_reservations, observed_no_shows
FROM forecast_input
WHERE seller_id = :p1
"""


GET_FORECAST_OUTPUT_BY_BUNDLE = """-- name: get_forecast_output_by_bundle \\:one
SELECT output_id, bundle_id, seller_id, window_start, predicted_sales, posted_qty, predicted_no_show_prob, confidence, rationale, generated_at
FROM forecast_output
WHERE bundle_id = :p1
LIMIT 1
"""


GET_FORECAST_OUTPUTS_BY_SELLER = """-- name: get_forecast_outputs_by_seller \\:many
SELECT output_id, bundle_id, seller_id, window_start, predicted_sales, posted_qty, predicted_no_show_prob, confidence, rationale, generated_at
FROM forecast_output
WHERE seller_id = :p1
ORDER BY window_start
"""


UPSERT_FORECAST_OUTPUT = """-- name: upsert_forecast_output \\:one
INSERT INTO forecast_output (bundle_id, seller_id, window_start, predicted_sales, posted_qty, predicted_no_show_prob, confidence, rationale)
VALUES (:p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8)
ON CONFLICT (bundle_id) DO UPDATE SET
    predicted_sales = EXCLUDED.predicted_sales,
    posted_qty = EXCLUDED.posted_qty,
    predicted_no_show_prob = EXCLUDED.predicted_no_show_prob,
    confidence = EXCLUDED.confidence,
    rationale = EXCLUDED.rationale,
    generated_at = CURRENT_TIMESTAMP
RETURNING output_id, bundle_id, seller_id, window_start, predicted_sales, posted_qty, predicted_no_show_prob, confidence, rationale, generated_at
"""


class UpsertForecastOutputParams(pydantic.BaseModel):
    bundle_id: int
    seller_id: int
    window_start: datetime.datetime
    predicted_sales: int
    posted_qty: int
    predicted_no_show_prob: decimal.Decimal
    confidence: decimal.Decimal
    rationale: Optional[str]


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_forecast_input(self, arg: CreateForecastInputParams) -> Optional[models.ForecastInput]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_FORECAST_INPUT), {
            "p1": arg.bundle_id,
            "p2": arg.seller_id,
            "p3": arg.category_id,
            "p4": arg.day_of_week,
            "p5": arg.window_start,
            "p6": arg.window_end,
            "p7": arg.is_holiday,
            "p8": arg.temperature,
            "p9": arg.weather_flag,
            "p10": arg.observed_reservations,
            "p11": arg.observed_no_shows,
        })).first()
        if row is None:
            return None
        return models.ForecastInput(
            input_id=row[0],
            bundle_id=row[1],
            seller_id=row[2],
            category_id=row[3],
            day_of_week=row[4],
            window_start=row[5],
            window_end=row[6],
            is_holiday=row[7],
            temperature=row[8],
            weather_flag=row[9],
            observed_reservations=row[10],
            observed_no_shows=row[11],
        )

    async def get_forecast_inputs_by_seller(self, *, seller_id: int) -> AsyncIterator[models.ForecastInput]:
        result = await self._conn.stream(sqlalchemy.text(GET_FORECAST_INPUTS_BY_SELLER), {"p1": seller_id})
        async for row in result:
            yield models.ForecastInput(
                input_id=row[0],
                bundle_id=row[1],
                seller_id=row[2],
                category_id=row[3],
                day_of_week=row[4],
                window_start=row[5],
                window_end=row[6],
                is_holiday=row[7],
                temperature=row[8],
                weather_flag=row[9],
                observed_reservations=row[10],
                observed_no_shows=row[11],
            )

    async def get_forecast_output_by_bundle(self, *, bundle_id: int) -> Optional[models.ForecastOutput]:
        row = (await self._conn.execute(sqlalchemy.text(GET_FORECAST_OUTPUT_BY_BUNDLE), {"p1": bundle_id})).first()
        if row is None:
            return None
        return models.ForecastOutput(
            output_id=row[0],
            bundle_id=row[1],
            seller_id=row[2],
            window_start=row[3],
            predicted_sales=row[4],
            posted_qty=row[5],
            predicted_no_show_prob=row[6],
            confidence=row[7],
            rationale=row[8],
            generated_at=row[9],
        )

    async def get_forecast_outputs_by_seller(self, *, seller_id: int) -> AsyncIterator[models.ForecastOutput]:
        result = await self._conn.stream(sqlalchemy.text(GET_FORECAST_OUTPUTS_BY_SELLER), {"p1": seller_id})
        async for row in result:
            yield models.ForecastOutput(
                output_id=row[0],
                bundle_id=row[1],
                seller_id=row[2],
                window_start=row[3],
                predicted_sales=row[4],
                posted_qty=row[5],
                predicted_no_show_prob=row[6],
                confidence=row[7],
                rationale=row[8],
                generated_at=row[9],
            )

    async def upsert_forecast_output(self, arg: UpsertForecastOutputParams) -> Optional[models.ForecastOutput]:
        row = (await self._conn.execute(sqlalchemy.text(UPSERT_FORECAST_OUTPUT), {
            "p1": arg.bundle_id,
            "p2": arg.seller_id,
            "p3": arg.window_start,
            "p4": arg.predicted_sales,
            "p5": arg.posted_qty,
            "p6": arg.predicted_no_show_prob,
            "p7": arg.confidence,
            "p8": arg.rationale,
        })).first()
        if row is None:
            return None
        return models.ForecastOutput(
            output_id=row[0],
            bundle_id=row[1],
            seller_id=row[2],
            window_start=row[3],
            predicted_sales=row[4],
            posted_qty=row[5],
            predicted_no_show_prob=row[6],
            confidence=row[7],
            rationale=row[8],
            generated_at=row[9],
        )
