# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: inbox.sql
import pydantic
from typing import AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


CREATE_INBOX_MESSAGE = """-- name: create_inbox_message \\:one
INSERT INTO inbox (user_id, sender_id, message_subject, message_text)
VALUES (:p1, :p2, :p3, :p4)
RETURNING message_id, user_id, sender_id, message_subject, message_text, sent_at, read_status
"""


class CreateInboxMessageParams(pydantic.BaseModel):
    user_id: int
    sender_id: int
    message_subject: str
    message_text: str


GET_INBOXES = """-- name: get_inboxes \\:many
SELECT message_id, user_id, sender_id, message_subject, message_text, sent_at, read_status
FROM inbox
"""


GET_USER_INBOX = """-- name: get_user_inbox \\:many
SELECT message_id, user_id, sender_id, message_subject, message_text, sent_at, read_status
FROM inbox
WHERE user_id = :p1
"""


READ_INBOX_MESSAGE = """-- name: read_inbox_message \\:one
UPDATE inbox
SET read_status = TRUE
WHERE message_id = :p1
RETURNING message_id, user_id, sender_id, message_subject, message_text, sent_at, read_status
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_inbox_message(self, arg: CreateInboxMessageParams) -> Optional[models.Inbox]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_INBOX_MESSAGE), {
            "p1": arg.user_id,
            "p2": arg.sender_id,
            "p3": arg.message_subject,
            "p4": arg.message_text,
        })).first()
        if row is None:
            return None
        return models.Inbox(
            message_id=row[0],
            user_id=row[1],
            sender_id=row[2],
            message_subject=row[3],
            message_text=row[4],
            sent_at=row[5],
            read_status=row[6],
        )

    async def get_inboxes(self) -> AsyncIterator[models.Inbox]:
        result = await self._conn.stream(sqlalchemy.text(GET_INBOXES))
        async for row in result:
            yield models.Inbox(
                message_id=row[0],
                user_id=row[1],
                sender_id=row[2],
                message_subject=row[3],
                message_text=row[4],
                sent_at=row[5],
                read_status=row[6],
            )

    async def get_user_inbox(self, *, user_id: int) -> AsyncIterator[models.Inbox]:
        result = await self._conn.stream(sqlalchemy.text(GET_USER_INBOX), {"p1": user_id})
        async for row in result:
            yield models.Inbox(
                message_id=row[0],
                user_id=row[1],
                sender_id=row[2],
                message_subject=row[3],
                message_text=row[4],
                sent_at=row[5],
                read_status=row[6],
            )

    async def read_inbox_message(self, *, message_id: int) -> Optional[models.Inbox]:
        row = (await self._conn.execute(sqlalchemy.text(READ_INBOX_MESSAGE), {"p1": message_id})).first()
        if row is None:
            return None
        return models.Inbox(
            message_id=row[0],
            user_id=row[1],
            sender_id=row[2],
            message_subject=row[3],
            message_text=row[4],
            sent_at=row[5],
            read_status=row[6],
        )
