# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
<<<<<<< HEAD
import dataclasses
import enum
from typing import Any, Optional


class AdminIssueReportsIssueType(str, enum.Enum):
=======
import datetime
import decimal
import enum
import pydantic
from typing import Optional


class AdminIssueType(str, enum.Enum):
>>>>>>> origin/release
    LOGIN_FAILED = "LOGIN_FAILED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    QR_CODE_NOT_GENERATED = "QR_CODE_NOT_GENERATED"
    QR_CODE_SCAN_ERROR = "QR_CODE_SCAN_ERROR"
    APP_CRASH = "APP_CRASH"
    DATA_INCONSISTENCY = "DATA_INCONSISTENCY"
    PERMISSION_ERROR = "PERMISSION_ERROR"
    OTHER = "OTHER"


<<<<<<< HEAD
class AdminIssueReportsStatus(str, enum.Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    CLOSED = "closed"


class ForecastInputDayOfWeek(str, enum.Enum):
=======
class DayOfWeek(str, enum.Enum):
>>>>>>> origin/release
    MONDAY = "Monday"
    TUESDAY = "Tuesday"
    WEDNESDAY = "Wednesday"
    THURSDAY = "Thursday"
    FRIDAY = "Friday"
    SATURDAY = "Saturday"
    SUNDAY = "Sunday"


<<<<<<< HEAD
class ForecastInputWeatherFlag(str, enum.Enum):
    SUNNY = "sunny"
    CLOUDY = "cloudy"
    RAINY = "rainy"
    SNOWY = "snowy"
    WINDY = "windy"


class ReservationsStatus(str, enum.Enum):
=======
class IssueStatus(str, enum.Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    CLOSED = "closed"


class ReservationStatus(str, enum.Enum):
>>>>>>> origin/release
    RESERVED = "reserved"
    COLLECTED = "collected"
    NO_SHOW = "no_show"


<<<<<<< HEAD
class SellerIssueReportsIssueType(str, enum.Enum):
=======
class SellerIssueType(str, enum.Enum):
>>>>>>> origin/release
    ITEM_MISSING = "ITEM_MISSING"
    ITEM_INCORRECT = "ITEM_INCORRECT"
    ITEM_DAMAGED = "ITEM_DAMAGED"
    SELLER_CLOSED = "SELLER_CLOSED"
    SELLER_REFUSED_PICKUP = "SELLER_REFUSED_PICKUP"
    PICKUP_DELAYED = "PICKUP_DELAYED"
    BUNDLE_EXPIRED = "BUNDLE_EXPIRED"
    RESERVATION_CANCELLED_BY_SELLER = "RESERVATION_CANCELLED_BY_SELLER"
    RESERVATION_NOT_FOUND = "RESERVATION_NOT_FOUND"
    CLAIM_CODE_INVALID = "CLAIM_CODE_INVALID"
    CLAIM_CODE_ALREADY_USED = "CLAIM_CODE_ALREADY_USED"
    OTHER = "OTHER"


<<<<<<< HEAD
class SellerIssueReportsStatus(str, enum.Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    CLOSED = "closed"


class UsersRole(str, enum.Enum):
=======
class UserRole(str, enum.Enum):
>>>>>>> origin/release
    SELLER = "seller"
    CONSUMER = "consumer"
    ADMIN = "admin"


<<<<<<< HEAD
@dataclasses.dataclass()
class Admin:
    user_id: Any
    fname: Any
    lname: Any


@dataclasses.dataclass()
class AdminIssueReport:
    report_id: Any
    user_id: Any
    issue_type: Any
    description: Any
    created_at: Any
    status: Any


@dataclasses.dataclass()
class Allergen:
    allergen_id: Any
    allergen_name: Any


@dataclasses.dataclass()
class Badge:
    badge_id: Any
    name: Any
    description: Any


@dataclasses.dataclass()
class BadgesAcquired:
    user_id: Any
    badge_id: Any
    acquired_at: Any


@dataclasses.dataclass()
class Bundle:
    bundle_id: Any
    seller_id: Any
    bundle_name: Any
    description: Any
    total_qty: Any
    price: Any
    discount_percentage: Any
    window_start: Any
    window_end: Any
    created_at: Any


@dataclasses.dataclass()
class BundleAllergen:
    bundle_id: Any
    allergen_id: Any


@dataclasses.dataclass()
class BundleCategory:
    category_id: Any
    bundle_id: Any


@dataclasses.dataclass()
class Category:
    category_id: Any
    category_name: Any


@dataclasses.dataclass()
class Consumer:
    user_id: Any
    fname: Any
    lname: Any


@dataclasses.dataclass()
class ForecastInput:
    input_id: Any
    seller_id: Any
    category_id: Any
    day_of_week: Any
    window_start_hour: Any
    window_end_hour: Any
    is_holiday: Any
    temperature: Any
    weather_flag: Any
    observed_reservations: Any
    observed_no_shows: Any


@dataclasses.dataclass()
class ForecastOutput:
    output_id: Any
    bundle_id: Any
    predicted_reservations: Any
    predicted_no_show_prob: Any
    confidence: Any
    rationale: Optional[Any]
    generated_at: Any


@dataclasses.dataclass()
class Inbox:
    message_id: Any
    user_id: Any
    sender_id: Any
    message_subject: Any
    message_text: Any
    sent_at: Any
    read_status: Any


@dataclasses.dataclass()
class Reservation:
    reservation_id: Any
    bundle_id: Any
    consumer_id: Any
    reserved_at: Any
    claim_code: Any
    status: Any
    collected_at: Optional[Any]


@dataclasses.dataclass()
class Seller:
    user_id: Any
    seller_name: Any
    verified_by: Optional[Any]
    verification_date: Optional[Any]
    address_line1: Any
    address_line2: Optional[Any]
    city: Any
    post_code: Any
    region: Optional[Any]
    country: Any


@dataclasses.dataclass()
class SellerIssueReport:
    report_id: Any
    reservation_id: Any
    issue_type: Any
    description: Any
    created_at: Any
    status: Any


@dataclasses.dataclass()
class Token:
    token_id: Any
    user_id: Any
    token: Any
    created_at: Any
    expires_at: Any


@dataclasses.dataclass()
class User:
    user_id: Any
    email: Any
    pw_hash: Any
    role: Any
    created_at: Any
    last_login: Any
=======
class WeatherFlag(str, enum.Enum):
    SUNNY = "sunny"
    CLOUDY = "cloudy"
    RAINY = "rainy"
    SNOWY = "snowy"
    WINDY = "windy"


class Admin(pydantic.BaseModel):
    user_id: int
    fname: str
    lname: str


class AdminIssueReport(pydantic.BaseModel):
    report_id: int
    user_id: int
    issue_type: AdminIssueType
    description: str
    created_at: datetime.datetime
    status: IssueStatus


class Allergen(pydantic.BaseModel):
    allergen_id: int
    allergen_name: str


class Badge(pydantic.BaseModel):
    badge_id: int
    name: str
    description: str


class BadgesAcquired(pydantic.BaseModel):
    user_id: int
    badge_id: int
    acquired_at: datetime.datetime


class Bundle(pydantic.BaseModel):
    bundle_id: int
    seller_id: int
    bundle_name: str
    description: str
    total_qty: int
    price: decimal.Decimal
    discount_percentage: int
    window_start: datetime.datetime
    window_end: datetime.datetime
    created_at: datetime.datetime


class BundleAllergen(pydantic.BaseModel):
    bundle_id: int
    allergen_id: int


class BundleCategory(pydantic.BaseModel):
    category_id: int
    bundle_id: int


class Category(pydantic.BaseModel):
    category_id: int
    category_name: str


class Consumer(pydantic.BaseModel):
    user_id: int
    fname: str
    lname: str


class ForecastInput(pydantic.BaseModel):
    input_id: int
    seller_id: int
    category_id: int
    day_of_week: DayOfWeek
    window_start_hour: datetime.time
    window_end_hour: datetime.time
    is_holiday: bool
    temperature: decimal.Decimal
    weather_flag: WeatherFlag
    observed_reservations: int
    observed_no_shows: int


class ForecastOutput(pydantic.BaseModel):
    output_id: int
    bundle_id: int
    predicted_reservations: int
    predicted_no_show_prob: decimal.Decimal
    confidence: decimal.Decimal
    rationale: Optional[str]
    generated_at: datetime.datetime


class Inbox(pydantic.BaseModel):
    message_id: int
    user_id: int
    sender_id: int
    message_subject: str
    message_text: str
    sent_at: datetime.datetime
    read_status: bool


class Reservation(pydantic.BaseModel):
    reservation_id: int
    bundle_id: int
    consumer_id: int
    reserved_at: datetime.datetime
    claim_code: str
    status: ReservationStatus
    collected_at: Optional[datetime.datetime]


class Seller(pydantic.BaseModel):
    user_id: int
    seller_name: str
    verified_by: Optional[int]
    verification_date: Optional[datetime.datetime]
    address_line1: str
    address_line2: Optional[str]
    city: str
    post_code: str
    region: Optional[str]
    country: str


class SellerIssueReport(pydantic.BaseModel):
    report_id: int
    reservation_id: int
    issue_type: Optional[SellerIssueType]
    description: str
    created_at: datetime.datetime
    status: IssueStatus


class Token(pydantic.BaseModel):
    token_id: int
    user_id: int
    token: str
    created_at: datetime.datetime
    expires_at: datetime.datetime


class User(pydantic.BaseModel):
    user_id: int
    email: str
    pw_hash: str
    role: UserRole
    created_at: datetime.datetime
    last_login: datetime.datetime
>>>>>>> origin/release
