# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import datetime
import decimal
import enum
from typing import Optional


class AdminIssueType(str, enum.Enum):
    LOGIN_FAILED = "LOGIN_FAILED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    QR_CODE_NOT_GENERATED = "QR_CODE_NOT_GENERATED"
    QR_CODE_SCAN_ERROR = "QR_CODE_SCAN_ERROR"
    APP_CRASH = "APP_CRASH"
    DATA_INCONSISTENCY = "DATA_INCONSISTENCY"
    PERMISSION_ERROR = "PERMISSION_ERROR"
    OTHER = "OTHER"


class DayOfWeek(str, enum.Enum):
    MONDAY = "Monday"
    TUESDAY = "Tuesday"
    WEDNESDAY = "Wednesday"
    THURSDAY = "Thursday"
    FRIDAY = "Friday"
    SATURDAY = "Saturday"
    SUNDAY = "Sunday"


class IssueStatus(str, enum.Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    CLOSED = "closed"


class ReservationStatus(str, enum.Enum):
    RESERVED = "reserved"
    COLLECTED = "collected"
    NO_SHOW = "no_show"


class SellerIssueType(str, enum.Enum):
    ITEM_MISSING = "ITEM_MISSING"
    ITEM_INCORRECT = "ITEM_INCORRECT"
    ITEM_DAMAGED = "ITEM_DAMAGED"
    SELLER_CLOSED = "SELLER_CLOSED"
    SELLER_REFUSED_PICKUP = "SELLER_REFUSED_PICKUP"
    PICKUP_DELAYED = "PICKUP_DELAYED"
    BUNDLE_EXPIRED = "BUNDLE_EXPIRED"
    RESERVATION_CANCELLED_BY_SELLER = "RESERVATION_CANCELLED_BY_SELLER"
    RESERVATION_NOT_FOUND = "RESERVATION_NOT_FOUND"
    CLAIM_CODE_INVALID = "CLAIM_CODE_INVALID"
    CLAIM_CODE_ALREADY_USED = "CLAIM_CODE_ALREADY_USED"
    OTHER = "OTHER"


class UserRole(str, enum.Enum):
    SELLER = "seller"
    CONSUMER = "consumer"
    ADMIN = "admin"


class WeatherFlag(str, enum.Enum):
    SUNNY = "sunny"
    CLOUDY = "cloudy"
    RAINY = "rainy"
    SNOWY = "snowy"
    WINDY = "windy"


@dataclasses.dataclass()
class Admin:
    user_id: int
    fname: str
    lname: str


@dataclasses.dataclass()
class AdminIssueReport:
    report_id: int
    user_id: int
    issue_type: AdminIssueType
    description: str
    created_at: datetime.datetime
    status: IssueStatus


@dataclasses.dataclass()
class Allergen:
    allergen_id: int
    allergen_name: str


@dataclasses.dataclass()
class Badge:
    badge_id: int
    name: str
    description: str


@dataclasses.dataclass()
class BadgesAcquired:
    user_id: int
    badge_id: int
    acquired_at: datetime.datetime


@dataclasses.dataclass()
class Bundle:
    bundle_id: int
    seller_id: int
    bundle_name: str
    description: str
    total_qty: int
    price: decimal.Decimal
    discount_percentage: int
    window_start: datetime.datetime
    window_end: datetime.datetime
    created_at: datetime.datetime


@dataclasses.dataclass()
class BundleAllergen:
    bundle_id: int
    allergen_id: int


@dataclasses.dataclass()
class BundleCategory:
    category_id: int
    bundle_id: int


@dataclasses.dataclass()
class Category:
    category_id: int
    category_name: str


@dataclasses.dataclass()
class Consumer:
    user_id: int
    fname: str
    lname: str


@dataclasses.dataclass()
class ForecastInput:
    input_id: int
    seller_id: int
    category_id: int
    day_of_week: DayOfWeek
    window_start_hour: datetime.time
    window_end_hour: datetime.time
    is_holiday: bool
    temperature: decimal.Decimal
    weather_flag: WeatherFlag
    observed_reservations: int
    observed_no_shows: int


@dataclasses.dataclass()
class ForecastOutput:
    output_id: int
    bundle_id: int
    predicted_reservations: int
    predicted_no_show_prob: decimal.Decimal
    confidence: decimal.Decimal
    rationale: Optional[str]
    generated_at: datetime.datetime


@dataclasses.dataclass()
class Inbox:
    message_id: int
    user_id: int
    sender_id: int
    message_subject: str
    message_text: str
    sent_at: datetime.datetime
    read_status: bool


@dataclasses.dataclass()
class Reservation:
    reservation_id: int
    bundle_id: int
    consumer_id: int
    reserved_at: datetime.datetime
    claim_code: str
    status: ReservationStatus
    collected_at: Optional[datetime.datetime]


@dataclasses.dataclass()
class Seller:
    user_id: int
    seller_name: str
    verified_by: Optional[int]
    verification_date: Optional[datetime.datetime]
    address_line1: str
    address_line2: Optional[str]
    city: str
    post_code: str
    region: Optional[str]
    country: str


@dataclasses.dataclass()
class SellerIssueReport:
    report_id: int
    reservation_id: int
    issue_type: Optional[SellerIssueType]
    description: str
    created_at: datetime.datetime
    status: IssueStatus


@dataclasses.dataclass()
class Token:
    token_id: int
    user_id: int
    token: str
    created_at: datetime.datetime
    expires_at: datetime.datetime


@dataclasses.dataclass()
class User:
    user_id: int
    email: str
    pw_hash: str
    role: UserRole
    created_at: datetime.datetime
    last_login: datetime.datetime
