# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import enum
from typing import Any, Optional


class AdminIssueReportsIssueType(str, enum.Enum):
    LOGIN_FAILED = "LOGIN_FAILED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    QR_CODE_NOT_GENERATED = "QR_CODE_NOT_GENERATED"
    QR_CODE_SCAN_ERROR = "QR_CODE_SCAN_ERROR"
    APP_CRASH = "APP_CRASH"
    DATA_INCONSISTENCY = "DATA_INCONSISTENCY"
    PERMISSION_ERROR = "PERMISSION_ERROR"
    OTHER = "OTHER"


class AdminIssueReportsStatus(str, enum.Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    CLOSED = "closed"


class ForecastInputDayOfWeek(str, enum.Enum):
    MONDAY = "Monday"
    TUESDAY = "Tuesday"
    WEDNESDAY = "Wednesday"
    THURSDAY = "Thursday"
    FRIDAY = "Friday"
    SATURDAY = "Saturday"
    SUNDAY = "Sunday"


class ForecastInputWeatherFlag(str, enum.Enum):
    SUNNY = "sunny"
    CLOUDY = "cloudy"
    RAINY = "rainy"
    SNOWY = "snowy"
    WINDY = "windy"


class ReservationsStatus(str, enum.Enum):
    RESERVED = "reserved"
    COLLECTED = "collected"
    NO_SHOW = "no_show"


class SellerIssueReportsIssueType(str, enum.Enum):
    ITEM_MISSING = "ITEM_MISSING"
    ITEM_INCORRECT = "ITEM_INCORRECT"
    ITEM_DAMAGED = "ITEM_DAMAGED"
    SELLER_CLOSED = "SELLER_CLOSED"
    SELLER_REFUSED_PICKUP = "SELLER_REFUSED_PICKUP"
    PICKUP_DELAYED = "PICKUP_DELAYED"
    BUNDLE_EXPIRED = "BUNDLE_EXPIRED"
    RESERVATION_CANCELLED_BY_SELLER = "RESERVATION_CANCELLED_BY_SELLER"
    RESERVATION_NOT_FOUND = "RESERVATION_NOT_FOUND"
    CLAIM_CODE_INVALID = "CLAIM_CODE_INVALID"
    CLAIM_CODE_ALREADY_USED = "CLAIM_CODE_ALREADY_USED"
    OTHER = "OTHER"


class SellerIssueReportsStatus(str, enum.Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    CLOSED = "closed"


class UsersRole(str, enum.Enum):
    SELLER = "seller"
    CONSUMER = "consumer"
    ADMIN = "admin"


@dataclasses.dataclass()
class Admin:
    user_id: Any
    fname: Any
    lname: Any


@dataclasses.dataclass()
class AdminIssueReport:
    report_id: Any
    user_id: Any
    issue_type: Any
    description: Any
    created_at: Any
    status: Any


@dataclasses.dataclass()
class Allergen:
    allergen_id: Any
    allergen_name: Any


@dataclasses.dataclass()
class Badge:
    badge_id: Any
    name: Any
    description: Any


@dataclasses.dataclass()
class BadgesAcquired:
    user_id: Any
    badge_id: Any
    acquired_at: Any


@dataclasses.dataclass()
class Bundle:
    bundle_id: Any
    seller_id: Any
    bundle_name: Any
    description: Any
    total_qty: Any
    price: Any
    discount_percentage: Any
    window_start: Any
    window_end: Any
    created_at: Any


@dataclasses.dataclass()
class BundleAllergen:
    bundle_id: Any
    allergen_id: Any


@dataclasses.dataclass()
class BundleCategory:
    category_id: Any
    bundle_id: Any


@dataclasses.dataclass()
class Category:
    category_id: Any
    category_name: Any


@dataclasses.dataclass()
class Consumer:
    user_id: Any
    fname: Any
    lname: Any


@dataclasses.dataclass()
class ForecastInput:
    input_id: Any
    seller_id: Any
    category_id: Any
    day_of_week: Any
    window_start_hour: Any
    window_end_hour: Any
    is_holiday: Any
    temperature: Any
    weather_flag: Any
    observed_reservations: Any
    observed_no_shows: Any


@dataclasses.dataclass()
class ForecastOutput:
    output_id: Any
    bundle_id: Any
    predicted_reservations: Any
    predicted_no_show_prob: Any
    confidence: Any
    rationale: Optional[Any]
    generated_at: Any


@dataclasses.dataclass()
class Inbox:
    message_id: Any
    user_id: Any
    sender_id: Any
    message_subject: Any
    message_text: Any
    sent_at: Any
    read_status: Any


@dataclasses.dataclass()
class Reservation:
    reservation_id: Any
    bundle_id: Any
    consumer_id: Any
    reserved_at: Any
    claim_code: Any
    status: Any
    collected_at: Optional[Any]


@dataclasses.dataclass()
class Seller:
    user_id: Any
    seller_name: Any
    verified_by: Optional[Any]
    verification_date: Optional[Any]
    address_line1: Any
    address_line2: Optional[Any]
    city: Any
    post_code: Any
    region: Optional[Any]
    country: Any


@dataclasses.dataclass()
class SellerIssueReport:
    report_id: Any
    reservation_id: Any
    issue_type: Any
    description: Any
    created_at: Any
    status: Any


@dataclasses.dataclass()
class Token:
    token_id: Any
    user_id: Any
    token: Any
    created_at: Any
    expires_at: Any


@dataclasses.dataclass()
class User:
    user_id: Any
    email: Any
    pw_hash: Any
    role: Any
    created_at: Any
    last_login: Any
