# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: reservations.sql
import datetime
import pydantic
from typing import Any, AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


COLLECT_RESERVATION = """-- name: collect_reservation \\:one
UPDATE reservations
SET collected_at=NOW()
WHERE reservation_id=:p1
RETURNING reservation_id, bundle_id, consumer_id, reserved_at, claim_code, collected_at
"""


COUNT_CONSUMER_COLLECTED_RESERVATIONS = """-- name: count_consumer_collected_reservations \\:one
SELECT COUNT(*) AS collected_count, CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS has_collected
FROM reservations
WHERE consumer_id=:p1 AND collected_at IS NOT NULL
"""


class CountConsumerCollectedReservationsRow(pydantic.BaseModel):
    collected_count: int
    has_collected: int


CREATE_RESERVATION = """-- name: create_reservation \\:one
INSERT INTO reservations (bundle_id, consumer_id, claim_code)
VALUES (:p1,:p2,:p3)
RETURNING reservation_id, bundle_id, consumer_id, reserved_at, claim_code, collected_at
"""


class CreateReservationParams(pydantic.BaseModel):
    bundle_id: int
    consumer_id: int
    claim_code: str


DELETE_RESERVATION = """-- name: delete_reservation \\:one
DELETE FROM reservations
WHERE reservation_id = :p1
RETURNING reservation_id, bundle_id, consumer_id, reserved_at, claim_code, collected_at
"""


GET_BUNDLE_RESERVATIONS = """-- name: get_bundle_reservations \\:many
SELECT reservation_id, bundle_id, consumer_id, reserved_at, claim_code, collected_at
FROM reservations
WHERE bundle_id=:p1
"""


GET_CONSUMERS_RESERVATIONS = """-- name: get_consumers_reservations \\:many
SELECT reservation_id, bundle_id, consumer_id, reserved_at, claim_code, collected_at
FROM reservations
WHERE consumer_id=:p1
"""


GET_CONSUMERS_RESERVATIONS_FULL = """-- name: get_consumers_reservations_full \\:many
SELECT r.reservation_id, r.bundle_id, r.reserved_at, r.collected_at, b.seller_id, b.carbon_dioxide, b.window_start, b.window_end, array_agg(bc.category_id) AS category_ids
FROM reservations r
INNER JOIN bundles b ON b.bundle_id = r.bundle_id
LEFT JOIN bundle_category bc ON bc.bundle_id = r.bundle_id
WHERE consumer_id=:p1
GROUP BY r.reservation_id, r.bundle_id, r.reserved_at, r.collected_at, b.seller_id, b.carbon_dioxide, b.window_start, b.window_end
"""


class GetConsumersReservationsFullRow(pydantic.BaseModel):
    reservation_id: int
    bundle_id: int
    reserved_at: datetime.datetime
    collected_at: Optional[datetime.datetime]
    seller_id: int
    carbon_dioxide: int
    window_start: datetime.datetime
    window_end: datetime.datetime
    category_ids: Any


GET_RESERVATION = """-- name: get_reservation \\:one
SELECT reservation_id, bundle_id, consumer_id, reserved_at, claim_code, collected_at
FROM reservations
WHERE reservation_id=:p1
"""


GET_RESERVATION_COLLECTION = """-- name: get_reservation_collection \\:one
SELECT reservation_id, bundle_id, consumer_id, reserved_at, claim_code, collected_at
FROM reservations
WHERE bundle_id=:p1 AND claim_code=:p2 AND collected_at IS NULL
LIMIT 1
"""


class GetReservationCollectionParams(pydantic.BaseModel):
    bundle_id: int
    claim_code: str


GET_RESERVATIONS = """-- name: get_reservations \\:many
SELECT reservation_id, bundle_id, consumer_id, reserved_at, claim_code, collected_at FROM reservations
"""


GET_SELLER_RESERVATIONS_FULL = """-- name: get_seller_reservations_full \\:many
SELECT r.reservation_id, r.bundle_id, r.reserved_at, r.collected_at, b.carbon_dioxide, b.window_start, b.window_end, array_agg(bc.category_id) AS category_ids
FROM reservations r
INNER JOIN bundles b ON b.bundle_id = r.bundle_id
LEFT JOIN bundle_category bc ON bc.bundle_id = r.bundle_id
WHERE b.seller_id=:p1
GROUP BY r.reservation_id, r.bundle_id, r.reserved_at, r.collected_at, b.carbon_dioxide, b.window_start, b.window_end
"""


class GetSellerReservationsFullRow(pydantic.BaseModel):
    reservation_id: int
    bundle_id: int
    reserved_at: datetime.datetime
    collected_at: Optional[datetime.datetime]
    carbon_dioxide: int
    window_start: datetime.datetime
    window_end: datetime.datetime
    category_ids: Any


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def collect_reservation(self, *, reservation_id: int) -> Optional[models.Reservation]:
        row = (await self._conn.execute(sqlalchemy.text(COLLECT_RESERVATION), {"p1": reservation_id})).first()
        if row is None:
            return None
        return models.Reservation(
            reservation_id=row[0],
            bundle_id=row[1],
            consumer_id=row[2],
            reserved_at=row[3],
            claim_code=row[4],
            collected_at=row[5],
        )

    async def count_consumer_collected_reservations(self, *, consumer_id: int) -> Optional[CountConsumerCollectedReservationsRow]:
        row = (await self._conn.execute(sqlalchemy.text(COUNT_CONSUMER_COLLECTED_RESERVATIONS), {"p1": consumer_id})).first()
        if row is None:
            return None
        return CountConsumerCollectedReservationsRow(
            collected_count=row[0],
            has_collected=row[1],
        )

    async def create_reservation(self, arg: CreateReservationParams) -> Optional[models.Reservation]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_RESERVATION), {"p1": arg.bundle_id, "p2": arg.consumer_id, "p3": arg.claim_code})).first()
        if row is None:
            return None
        return models.Reservation(
            reservation_id=row[0],
            bundle_id=row[1],
            consumer_id=row[2],
            reserved_at=row[3],
            claim_code=row[4],
            collected_at=row[5],
        )

    async def delete_reservation(self, *, reservation_id: int) -> Optional[models.Reservation]:
        row = (await self._conn.execute(sqlalchemy.text(DELETE_RESERVATION), {"p1": reservation_id})).first()
        if row is None:
            return None
        return models.Reservation(
            reservation_id=row[0],
            bundle_id=row[1],
            consumer_id=row[2],
            reserved_at=row[3],
            claim_code=row[4],
            collected_at=row[5],
        )

    async def get_bundle_reservations(self, *, bundle_id: int) -> AsyncIterator[models.Reservation]:
        result = await self._conn.stream(sqlalchemy.text(GET_BUNDLE_RESERVATIONS), {"p1": bundle_id})
        async for row in result:
            yield models.Reservation(
                reservation_id=row[0],
                bundle_id=row[1],
                consumer_id=row[2],
                reserved_at=row[3],
                claim_code=row[4],
                collected_at=row[5],
            )

    async def get_consumers_reservations(self, *, consumer_id: int) -> AsyncIterator[models.Reservation]:
        result = await self._conn.stream(sqlalchemy.text(GET_CONSUMERS_RESERVATIONS), {"p1": consumer_id})
        async for row in result:
            yield models.Reservation(
                reservation_id=row[0],
                bundle_id=row[1],
                consumer_id=row[2],
                reserved_at=row[3],
                claim_code=row[4],
                collected_at=row[5],
            )

    async def get_consumers_reservations_full(self, *, consumer_id: int) -> AsyncIterator[GetConsumersReservationsFullRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_CONSUMERS_RESERVATIONS_FULL), {"p1": consumer_id})
        async for row in result:
            yield GetConsumersReservationsFullRow(
                reservation_id=row[0],
                bundle_id=row[1],
                reserved_at=row[2],
                collected_at=row[3],
                seller_id=row[4],
                carbon_dioxide=row[5],
                window_start=row[6],
                window_end=row[7],
                category_ids=row[8],
            )

    async def get_reservation(self, *, reservation_id: int) -> Optional[models.Reservation]:
        row = (await self._conn.execute(sqlalchemy.text(GET_RESERVATION), {"p1": reservation_id})).first()
        if row is None:
            return None
        return models.Reservation(
            reservation_id=row[0],
            bundle_id=row[1],
            consumer_id=row[2],
            reserved_at=row[3],
            claim_code=row[4],
            collected_at=row[5],
        )

    async def get_reservation_collection(self, arg: GetReservationCollectionParams) -> Optional[models.Reservation]:
        row = (await self._conn.execute(sqlalchemy.text(GET_RESERVATION_COLLECTION), {"p1": arg.bundle_id, "p2": arg.claim_code})).first()
        if row is None:
            return None
        return models.Reservation(
            reservation_id=row[0],
            bundle_id=row[1],
            consumer_id=row[2],
            reserved_at=row[3],
            claim_code=row[4],
            collected_at=row[5],
        )

    async def get_reservations(self) -> AsyncIterator[models.Reservation]:
        result = await self._conn.stream(sqlalchemy.text(GET_RESERVATIONS))
        async for row in result:
            yield models.Reservation(
                reservation_id=row[0],
                bundle_id=row[1],
                consumer_id=row[2],
                reserved_at=row[3],
                claim_code=row[4],
                collected_at=row[5],
            )

    async def get_seller_reservations_full(self, *, seller_id: int) -> AsyncIterator[GetSellerReservationsFullRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_SELLER_RESERVATIONS_FULL), {"p1": seller_id})
        async for row in result:
            yield GetSellerReservationsFullRow(
                reservation_id=row[0],
                bundle_id=row[1],
                reserved_at=row[2],
                collected_at=row[3],
                carbon_dioxide=row[4],
                window_start=row[5],
                window_end=row[6],
                category_ids=row[7],
            )
