# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: seller_issue_reports.sql
import pydantic
from typing import AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


DELETE_SELLER_ISSUE_REPORT = """-- name: delete_seller_issue_report \\:one
DELETE FROM seller_issue_reports
WHERE report_id = :p1
RETURNING report_id, reservation_id, issue_type, description, created_at, status
"""


GET_SELLER_ISSUE_REPORTS = """-- name: get_seller_issue_reports \\:many
SELECT report_id, reservation_id, issue_type, description, created_at, status FROM seller_issue_reports
"""


UPDATE_SELLER_ISSUE_REPORT_STATUS = """-- name: update_seller_issue_report_status \\:one
UPDATE seller_issue_reports
SET status = :p2
WHERE report_id = :p1
RETURNING report_id, reservation_id, issue_type, description, created_at, status
"""


class UpdateSellerIssueReportStatusParams(pydantic.BaseModel):
    report_id: int
    status: models.IssueStatus


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def delete_seller_issue_report(self, *, report_id: int) -> Optional[models.SellerIssueReport]:
        row = (await self._conn.execute(sqlalchemy.text(DELETE_SELLER_ISSUE_REPORT), {"p1": report_id})).first()
        if row is None:
            return None
        return models.SellerIssueReport(
            report_id=row[0],
            reservation_id=row[1],
            issue_type=row[2],
            description=row[3],
            created_at=row[4],
            status=row[5],
        )

    async def get_seller_issue_reports(self) -> AsyncIterator[models.SellerIssueReport]:
        result = await self._conn.stream(sqlalchemy.text(GET_SELLER_ISSUE_REPORTS))
        async for row in result:
            yield models.SellerIssueReport(
                report_id=row[0],
                reservation_id=row[1],
                issue_type=row[2],
                description=row[3],
                created_at=row[4],
                status=row[5],
            )

    async def update_seller_issue_report_status(self, arg: UpdateSellerIssueReportStatusParams) -> Optional[models.SellerIssueReport]:
        row = (await self._conn.execute(sqlalchemy.text(UPDATE_SELLER_ISSUE_REPORT_STATUS), {"p1": arg.report_id, "p2": arg.status})).first()
        if row is None:
            return None
        return models.SellerIssueReport(
            report_id=row[0],
            reservation_id=row[1],
            issue_type=row[2],
            description=row[3],
            created_at=row[4],
            status=row[5],
        )
