# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: seller.sql
import datetime
import pydantic
from typing import Iterator, Optional

import sqlalchemy

from internal.queries import models


CREATE_SELLER = """-- name: create_seller \\:one
INSERT INTO sellers (user_id, seller_name, address_line1, address_line2, city, post_code, region, country, latitude, longitude)
VALUES (:p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10)
RETURNING user_id, seller_name, verified_by, verification_date, address_line1, address_line2, city, post_code, region, country, latitude, longitude
"""


class CreateSellerParams(pydantic.BaseModel):
    user_id: int
    seller_name: str
    address_line1: str
    address_line2: Optional[str]
    city: str
    post_code: str
    region: Optional[str]
    country: str
    latitude: float
    longitude: float


GET_SELLER = """-- name: get_seller \\:one
SELECT u.user_id, u.username, u.email, s.seller_name, s.address_line1, s.address_line2, s.city, s.post_code, s.region, s.country, s.verified_by, s.verification_date, u.last_login, u.created_at, s.latitude, s.longitude
FROM sellers s
INNER JOIN users u ON s.user_id=u.user_id
WHERE u.user_id=:p1
LIMIT 1
"""


class GetSellerRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    seller_name: str
    address_line1: str
    address_line2: Optional[str]
    city: str
    post_code: str
    region: Optional[str]
    country: str
    verified_by: Optional[int]
    verification_date: Optional[datetime.datetime]
    last_login: datetime.datetime
    created_at: datetime.datetime
    latitude: float
    longitude: float


GET_SELLER_BY_LOCATION = """-- name: get_seller_by_location \\:many
SELECT u.user_id, u.username, u.email, s.seller_name, s.address_line1, s.address_line2, s.city, s.post_code, s.region, s.country, s.verified_by, s.verification_date, u.last_login, u.created_at, s.latitude, s.longitude
FROM sellers s
INNER JOIN users u ON s.user_id=u.user_id
WHERE s.latitude < :p1 AND s.latitude > :p2 AND s.longitude < :p3 AND s.longitude > :p4
"""


class GetSellerByLocationParams(pydantic.BaseModel):
    lat_max: float
    lat_min: float
    lon_max: float
    lon_min: float


class GetSellerByLocationRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    seller_name: str
    address_line1: str
    address_line2: Optional[str]
    city: str
    post_code: str
    region: Optional[str]
    country: str
    verified_by: Optional[int]
    verification_date: Optional[datetime.datetime]
    last_login: datetime.datetime
    created_at: datetime.datetime
    latitude: float
    longitude: float


GET_SELLERS = """-- name: get_sellers \\:many
SELECT u.user_id, u.username, u.email, s.seller_name, s.address_line1, s.address_line2, s.city, s.post_code, s.region, s.country, s.verified_by, s.verification_date, u.last_login, u.created_at, s.latitude, s.longitude
FROM sellers s
INNER JOIN users u ON s.user_id=u.user_id
"""


class GetSellersRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    seller_name: str
    address_line1: str
    address_line2: Optional[str]
    city: str
    post_code: str
    region: Optional[str]
    country: str
    verified_by: Optional[int]
    verification_date: Optional[datetime.datetime]
    last_login: datetime.datetime
    created_at: datetime.datetime
    latitude: float
    longitude: float


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_seller(self, arg: CreateSellerParams) -> Optional[models.Seller]:
        row = self._conn.execute(sqlalchemy.text(CREATE_SELLER), {
            "p1": arg.user_id,
            "p2": arg.seller_name,
            "p3": arg.address_line1,
            "p4": arg.address_line2,
            "p5": arg.city,
            "p6": arg.post_code,
            "p7": arg.region,
            "p8": arg.country,
            "p9": arg.latitude,
            "p10": arg.longitude,
        }).first()
        if row is None:
            return None
        return models.Seller(
            user_id=row[0],
            seller_name=row[1],
            verified_by=row[2],
            verification_date=row[3],
            address_line1=row[4],
            address_line2=row[5],
            city=row[6],
            post_code=row[7],
            region=row[8],
            country=row[9],
            latitude=row[10],
            longitude=row[11],
        )

    def get_seller(self, *, user_id: int) -> Optional[GetSellerRow]:
        row = self._conn.execute(sqlalchemy.text(GET_SELLER), {"p1": user_id}).first()
        if row is None:
            return None
        return GetSellerRow(
            user_id=row[0],
            username=row[1],
            email=row[2],
            seller_name=row[3],
            address_line1=row[4],
            address_line2=row[5],
            city=row[6],
            post_code=row[7],
            region=row[8],
            country=row[9],
            verified_by=row[10],
            verification_date=row[11],
            last_login=row[12],
            created_at=row[13],
            latitude=row[14],
            longitude=row[15],
        )

    def get_seller_by_location(self, arg: GetSellerByLocationParams) -> Iterator[GetSellerByLocationRow]:
        result = self._conn.execute(sqlalchemy.text(GET_SELLER_BY_LOCATION), {
            "p1": arg.lat_max,
            "p2": arg.lat_min,
            "p3": arg.lon_max,
            "p4": arg.lon_min,
        })
        for row in result:
            yield GetSellerByLocationRow(
                user_id=row[0],
                username=row[1],
                email=row[2],
                seller_name=row[3],
                address_line1=row[4],
                address_line2=row[5],
                city=row[6],
                post_code=row[7],
                region=row[8],
                country=row[9],
                verified_by=row[10],
                verification_date=row[11],
                last_login=row[12],
                created_at=row[13],
                latitude=row[14],
                longitude=row[15],
            )

    def get_sellers(self) -> Iterator[GetSellersRow]:
        result = self._conn.execute(sqlalchemy.text(GET_SELLERS))
        for row in result:
            yield GetSellersRow(
                user_id=row[0],
                username=row[1],
                email=row[2],
                seller_name=row[3],
                address_line1=row[4],
                address_line2=row[5],
                city=row[6],
                post_code=row[7],
                region=row[8],
                country=row[9],
                verified_by=row[10],
                verification_date=row[11],
                last_login=row[12],
                created_at=row[13],
                latitude=row[14],
                longitude=row[15],
            )
