# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: seller.sql
import dataclasses
from typing import Any, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from . import models


CREATE_SELLER = """-- name: create_seller \\:exec
INSERT INTO sellers (user_id, seller_name, address_line1, address_line2, city, post_code, region, country)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
"""


@dataclasses.dataclass()
class CreateSellerParams:
    user_id: Any
    seller_name: Any
    address_line1: Any
    address_line2: Optional[Any]
    city: Any
    post_code: Any
    region: Optional[Any]
    country: Any


GET_SELLER = """-- name: get_seller \\:one
SELECT users.user_id, email, seller_name, address_line1, address_line2, city, post_code, region, country, verified_by, verification_date
FROM sellers
INNER JOIN users ON sellers.user_id=users.user_od
WHERE users.user_id=?
LIMIT 1
"""


@dataclasses.dataclass()
class GetSellerRow:
    user_id: Any
    email: Any
    seller_name: Any
    address_line1: Any
    address_line2: Optional[Any]
    city: Any
    post_code: Any
    region: Optional[Any]
    country: Any
    verified_by: Optional[Any]
    verification_date: Optional[Any]


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_seller(self, arg: CreateSellerParams) -> None:
        self._conn.execute(sqlalchemy.text(CREATE_SELLER), {
            "p1": arg.user_id,
            "p2": arg.seller_name,
            "p3": arg.address_line1,
            "p4": arg.address_line2,
            "p5": arg.city,
            "p6": arg.post_code,
            "p7": arg.region,
            "p8": arg.country,
        })

    def get_seller(self, *, user_id: Any) -> Optional[GetSellerRow]:
        row = self._conn.execute(sqlalchemy.text(GET_SELLER), {"p1": user_id}).first()
        if row is None:
            return None
        return GetSellerRow(
            user_id=row[0],
            email=row[1],
            seller_name=row[2],
            address_line1=row[3],
            address_line2=row[4],
            city=row[5],
            post_code=row[6],
            region=row[7],
            country=row[8],
            verified_by=row[9],
            verification_date=row[10],
        )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_seller(self, arg: CreateSellerParams) -> None:
        await self._conn.execute(sqlalchemy.text(CREATE_SELLER), {
            "p1": arg.user_id,
            "p2": arg.seller_name,
            "p3": arg.address_line1,
            "p4": arg.address_line2,
            "p5": arg.city,
            "p6": arg.post_code,
            "p7": arg.region,
            "p8": arg.country,
        })

    async def get_seller(self, *, user_id: Any) -> Optional[GetSellerRow]:
        row = (await self._conn.execute(sqlalchemy.text(GET_SELLER), {"p1": user_id})).first()
        if row is None:
            return None
        return GetSellerRow(
            user_id=row[0],
            email=row[1],
            seller_name=row[2],
            address_line1=row[3],
            address_line2=row[4],
            city=row[5],
            post_code=row[6],
            region=row[7],
            country=row[8],
            verified_by=row[9],
            verification_date=row[10],
        )
