# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: seller.sql
import datetime
import pydantic
from typing import Optional

import sqlalchemy

from . import models


CREATE_SELLER = """-- name: create_seller \\:one
INSERT INTO sellers (user_id, seller_name, address_line1, address_line2, city, post_code, region, country)
VALUES (:p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8)
RETURNING user_id, seller_name, verified_by, verification_date, address_line1, address_line2, city, post_code, region, country
"""


class CreateSellerParams(pydantic.BaseModel):
    user_id: int
    seller_name: str
    address_line1: str
    address_line2: Optional[str]
    city: str
    post_code: str
    region: Optional[str]
    country: str


GET_SELLER = """-- name: get_seller \\:one
SELECT users.user_id, email, seller_name, address_line1, address_line2, city, post_code, region, country, verified_by, verification_date
FROM sellers
INNER JOIN users ON sellers.user_id=users.user_od
WHERE users.user_id=:p1
LIMIT 1
"""


class GetSellerRow(pydantic.BaseModel):
    user_id: int
    email: str
    seller_name: str
    address_line1: str
    address_line2: Optional[str]
    city: str
    post_code: str
    region: Optional[str]
    country: str
    verified_by: Optional[int]
    verification_date: Optional[datetime.datetime]


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_seller(self, arg: CreateSellerParams) -> Optional[models.Seller]:
        row = self._conn.execute(sqlalchemy.text(CREATE_SELLER), {
            "p1": arg.user_id,
            "p2": arg.seller_name,
            "p3": arg.address_line1,
            "p4": arg.address_line2,
            "p5": arg.city,
            "p6": arg.post_code,
            "p7": arg.region,
            "p8": arg.country,
        }).first()
        if row is None:
            return None
        return models.Seller(
            user_id=row[0],
            seller_name=row[1],
            verified_by=row[2],
            verification_date=row[3],
            address_line1=row[4],
            address_line2=row[5],
            city=row[6],
            post_code=row[7],
            region=row[8],
            country=row[9],
        )

    def get_seller(self, *, user_id: int) -> Optional[GetSellerRow]:
        row = self._conn.execute(sqlalchemy.text(GET_SELLER), {"p1": user_id}).first()
        if row is None:
            return None
        return GetSellerRow(
            user_id=row[0],
            email=row[1],
            seller_name=row[2],
            address_line1=row[3],
            address_line2=row[4],
            city=row[5],
            post_code=row[6],
            region=row[7],
            country=row[8],
            verified_by=row[9],
            verification_date=row[10],
        )
