# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: token.sql
import datetime
import pydantic
from typing import Iterator, Optional

import sqlalchemy

from . import models


CREATE_TOKEN = """-- name: create_token \\:one
INSERT INTO token (user_id, token, expires_at)
VALUES (:p1, :p2, :p3)
RETURNING token_id, user_id, token, created_at, expires_at
"""


DELETE_TOKEN = """-- name: delete_token \\:one
DELETE FROM token
WHERE token = :p1
RETURNING token_id, user_id, token, created_at, expires_at
"""


GET_SESSION_BY_TOKEN = """-- name: get_session_by_token \\:one
SELECT u.user_id, u.email, u.role, t.token, t.expires_at, t.created_at
FROM token t
JOIN users u ON u.user_id = t.user_id
WHERE t.token = :p1
AND t.expires_at > NOW()
LIMIT 1
"""


class GetSessionByTokenRow(pydantic.BaseModel):
    user_id: int
    email: str
    role: models.UserRole
    token: str
    expires_at: datetime.datetime
    created_at: datetime.datetime


GET_TOKEN_BY_TOKEN = """-- name: get_token_by_token \\:one
SELECT token_id, user_id, token, created_at, expires_at
FROM token
WHERE token = :p1
LIMIT 1
"""


GET_TOKENS_BY_USER = """-- name: get_tokens_by_user \\:many
SELECT token_id, user_id, token, created_at, expires_at
FROM token
WHERE user_id = :p1
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_token(self, *, user_id: int, token: str, expires_at: datetime.datetime) -> Optional[models.Token]:
        row = self._conn.execute(sqlalchemy.text(CREATE_TOKEN), {"p1": user_id, "p2": token, "p3": expires_at}).first()
        if row is None:
            return None
        return models.Token(
            token_id=row[0],
            user_id=row[1],
            token=row[2],
            created_at=row[3],
            expires_at=row[4],
        )

    def delete_token(self, *, token: str) -> Optional[models.Token]:
        row = self._conn.execute(sqlalchemy.text(DELETE_TOKEN), {"p1": token}).first()
        if row is None:
            return None
        return models.Token(
            token_id=row[0],
            user_id=row[1],
            token=row[2],
            created_at=row[3],
            expires_at=row[4],
        )

    def get_session_by_token(self, *, token: str) -> Optional[GetSessionByTokenRow]:
        row = self._conn.execute(sqlalchemy.text(GET_SESSION_BY_TOKEN), {"p1": token}).first()
        if row is None:
            return None
        return GetSessionByTokenRow(
            user_id=row[0],
            email=row[1],
            role=row[2],
            token=row[3],
            expires_at=row[4],
            created_at=row[5],
        )

    def get_token_by_token(self, *, token: str) -> Optional[models.Token]:
        row = self._conn.execute(sqlalchemy.text(GET_TOKEN_BY_TOKEN), {"p1": token}).first()
        if row is None:
            return None
        return models.Token(
            token_id=row[0],
            user_id=row[1],
            token=row[2],
            created_at=row[3],
            expires_at=row[4],
        )

    def get_tokens_by_user(self, *, user_id: int) -> Iterator[models.Token]:
        result = self._conn.execute(sqlalchemy.text(GET_TOKENS_BY_USER), {"p1": user_id})
        for row in result:
            yield models.Token(
                token_id=row[0],
                user_id=row[1],
                token=row[2],
                created_at=row[3],
                expires_at=row[4],
            )
