# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: user.sql
import datetime
import decimal
import pydantic
from typing import AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from internal.queries import models


CREATE_USER = """-- name: create_user \\:one
INSERT INTO users (email, username, pw_hash, role)
VALUES (:p1, :p2, :p3, :p4)
RETURNING user_id, username, email, role, created_at
"""


class CreateUserParams(pydantic.BaseModel):
    email: str
    username: str
    pw_hash: str
    role: models.UserRole


class CreateUserRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    role: models.UserRole
    created_at: datetime.datetime


DELETE_USER = """-- name: delete_user \\:one
DELETE FROM users
WHERE user_id = :p1
RETURNING user_id, username, email, role, created_at
"""


class DeleteUserRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    role: models.UserRole
    created_at: datetime.datetime


GET_USER = """-- name: get_user \\:one
SELECT user_id, username, email, role, created_at
FROM users
WHERE user_id = :p1 
LIMIT 1
"""


class GetUserRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    role: models.UserRole
    created_at: datetime.datetime


GET_USER_ID = """-- name: get_user_id \\:one
SELECT user_id
FROM users
WHERE username=:p1
LIMIT 1
"""


GET_USER_LOGIN = """-- name: get_user_login \\:one
SELECT user_id, username, email, pw_hash, role
FROM users
WHERE email = :p1
LIMIT 1
"""


class GetUserLoginRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    pw_hash: str
    role: models.UserRole


GET_USERS = """-- name: get_users \\:many
SELECT user_id, username, email, role, created_at, last_login
FROM users
"""


class GetUsersRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    role: models.UserRole
    created_at: datetime.datetime
    last_login: datetime.datetime


LEADERBOARD_CARBON_DIOXIDE = """-- name: leaderboard_carbon_dioxide \\:many
SELECT u.username, COALESCE(SUM(b.carbon_dioxide), 0)\\:\\:numeric AS total_carbon_dioxide
FROM users u
LEFT JOIN reservations r ON r.consumer_id = u.user_id
LEFT JOIN bundles b ON b.bundle_id = r.bundle_id
GROUP BY u.user_id, u.username
ORDER BY total_carbon_dioxide DESC
LIMIT :p1
"""


class LeaderboardCarbonDioxideRow(pydantic.BaseModel):
    username: str
    total_carbon_dioxide: decimal.Decimal


LEADERBOARD_RESERVATIONS = """-- name: leaderboard_reservations \\:many
SELECT u.username, COUNT(r.reservation_id) AS reservation_count
FROM users u
LEFT JOIN reservations r ON r.consumer_id = u.user_id
GROUP BY u.user_id, u.username
ORDER BY reservation_count DESC
LIMIT :p1
"""


class LeaderboardReservationsRow(pydantic.BaseModel):
    username: str
    reservation_count: int


UPDATE_USER_EMAIL = """-- name: update_user_email \\:one
UPDATE users
SET email=:p2
WHERE user_id=:p1
RETURNING user_id, username, email, role, created_at
"""


class UpdateUserEmailParams(pydantic.BaseModel):
    user_id: int
    email: str


class UpdateUserEmailRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    role: models.UserRole
    created_at: datetime.datetime


UPDATE_USER_PASSWORD = """-- name: update_user_password \\:one
UPDATE users
SET pw_hash=:p2
WHERE user_id=:p1
RETURNING user_id, username, email, role, created_at
"""


class UpdateUserPasswordParams(pydantic.BaseModel):
    user_id: int
    pw_hash: str


class UpdateUserPasswordRow(pydantic.BaseModel):
    user_id: int
    username: str
    email: str
    role: models.UserRole
    created_at: datetime.datetime


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_user(self, arg: CreateUserParams) -> Optional[CreateUserRow]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_USER), {
            "p1": arg.email,
            "p2": arg.username,
            "p3": arg.pw_hash,
            "p4": arg.role,
        })).first()
        if row is None:
            return None
        return CreateUserRow(
            user_id=row[0],
            username=row[1],
            email=row[2],
            role=row[3],
            created_at=row[4],
        )

    async def delete_user(self, *, user_id: int) -> Optional[DeleteUserRow]:
        row = (await self._conn.execute(sqlalchemy.text(DELETE_USER), {"p1": user_id})).first()
        if row is None:
            return None
        return DeleteUserRow(
            user_id=row[0],
            username=row[1],
            email=row[2],
            role=row[3],
            created_at=row[4],
        )

    async def get_user(self, *, user_id: int) -> Optional[GetUserRow]:
        row = (await self._conn.execute(sqlalchemy.text(GET_USER), {"p1": user_id})).first()
        if row is None:
            return None
        return GetUserRow(
            user_id=row[0],
            username=row[1],
            email=row[2],
            role=row[3],
            created_at=row[4],
        )

    async def get_user_id(self, *, username: str) -> Optional[int]:
        row = (await self._conn.execute(sqlalchemy.text(GET_USER_ID), {"p1": username})).first()
        if row is None:
            return None
        return row[0]

    async def get_user_login(self, *, email: str) -> Optional[GetUserLoginRow]:
        row = (await self._conn.execute(sqlalchemy.text(GET_USER_LOGIN), {"p1": email})).first()
        if row is None:
            return None
        return GetUserLoginRow(
            user_id=row[0],
            username=row[1],
            email=row[2],
            pw_hash=row[3],
            role=row[4],
        )

    async def get_users(self) -> AsyncIterator[GetUsersRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_USERS))
        async for row in result:
            yield GetUsersRow(
                user_id=row[0],
                username=row[1],
                email=row[2],
                role=row[3],
                created_at=row[4],
                last_login=row[5],
            )

    async def leaderboard_carbon_dioxide(self, *, limit: int) -> AsyncIterator[LeaderboardCarbonDioxideRow]:
        result = await self._conn.stream(sqlalchemy.text(LEADERBOARD_CARBON_DIOXIDE), {"p1": limit})
        async for row in result:
            yield LeaderboardCarbonDioxideRow(
                username=row[0],
                total_carbon_dioxide=row[1],
            )

    async def leaderboard_reservations(self, *, limit: int) -> AsyncIterator[LeaderboardReservationsRow]:
        result = await self._conn.stream(sqlalchemy.text(LEADERBOARD_RESERVATIONS), {"p1": limit})
        async for row in result:
            yield LeaderboardReservationsRow(
                username=row[0],
                reservation_count=row[1],
            )

    async def update_user_email(self, arg: UpdateUserEmailParams) -> Optional[UpdateUserEmailRow]:
        row = (await self._conn.execute(sqlalchemy.text(UPDATE_USER_EMAIL), {"p1": arg.user_id, "p2": arg.email})).first()
        if row is None:
            return None
        return UpdateUserEmailRow(
            user_id=row[0],
            username=row[1],
            email=row[2],
            role=row[3],
            created_at=row[4],
        )

    async def update_user_password(self, arg: UpdateUserPasswordParams) -> Optional[UpdateUserPasswordRow]:
        row = (await self._conn.execute(sqlalchemy.text(UPDATE_USER_PASSWORD), {"p1": arg.user_id, "p2": arg.pw_hash})).first()
        if row is None:
            return None
        return UpdateUserPasswordRow(
            user_id=row[0],
            username=row[1],
            email=row[2],
            role=row[3],
            created_at=row[4],
        )
