up:
	@podman-compose -f ./docker-compose.yaml up --build

up-detach:
	@podman-compose -f ./docker-compose.yaml up --build --detach

up-built:
	@podman-compose -f ./docker-compose.yaml up

up-built-detach:
	@podman-compose -f ./docker-compose.yaml up --detach

down:
	@podman-compose -f ./docker-compose.yaml down
