apiVersion: v1
kind: Secret
metadata:
  name: hail-mary-deployment-secret
  namespace: hail-mary
type: Opaque
stringData:
  host-port: "80"
  host-host: "0.0.0.0"
  database-host: hail-mary-postgres-rw
  database-port: "5432"
  database-database: hail-mary
