apiVersion: v1
kind: Service
metadata:
  name: hail-mary-frontend
  namespace: hail-mary
  labels:
    app: hail-mary-frontend
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: hail-mary-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hail-mary-frontend
  namespace: hail-mary
  labels:
    app: hail-mary-frontend
  annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hail-mary-frontend
  template:
    metadata:
      labels:
        app: hail-mary-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/misha-artemiev/hail-mary-com2020/hail-mary-com2020-frontend:1.4.11
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hail-mary-backend
  namespace: hail-mary
  labels:
    app: hail-mary-backend
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: hail-mary-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hail-mary-backend
  namespace: hail-mary
  labels:
    app: hail-mary-backend
  annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hail-mary-backend
  template:
    metadata:
      labels:
        app: hail-mary-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/misha-artemiev/hail-mary-com2020/hail-mary-com2020-backend:1.4.11
          imagePullPolicy: Always
          env:
            - name: HOST_PORT
              valueFrom:
                secretKeyRef:
                  name: hail-mary-deployment-secret
                  key: host-port
            - name: HOST_HOST
              valueFrom:
                secretKeyRef:
                  name: hail-mary-deployment-secret
                  key: host-host
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: hail-mary-deployment-secret
                  key: database-host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: hail-mary-deployment-secret
                  key: database-port
            - name: DATABASE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: hail-mary-deployment-secret
                  key: database-database
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hail-mary-postgres-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hail-mary-postgres-secret
                  key: password
            - name: BLOCK_URL_PORT
              valueFrom:
                secretKeyRef:
                  name: hail-mary-deployment-secret
                  key: block_url_port
            - name: BLOCK_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: hail-mary-minio-secret
                  key: access-key
            - name: BLOCK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hail-mary-minio-secret
                  key: secret-key
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
