name: pull request checks
on:
  pull_request:
    branches:
      - release
      - dev/backend
jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: check for version bump
        run: |
          set -e
          TARGET_BRANCH="origin/${{ github.base_ref }}"
          OLD_VER=$(git show $TARGET_BRANCH:frontend/package.json | jq -r .version)
          NEW_VER=$(jq -r .version frontend/package.json)
          LOWEST=$(printf '%s\n' "$OLD_VER" "$NEW_VER" | sort -V | head -n1)
          if [ "$LOWEST" = "$NEW_VER" ]; then
             exit 1
          fi
  backend-checks:
    needs: check-version-bump
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
          cache: 'pip'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: run checks
        run: make check
  frontend-checks:
    needs: check-version-bump
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v6
      - name: setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '25'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: install dependencies
        run: npm ci
      - name: run checks
        run: |
          npm run lint
          npm run format
